#!/bin/sh

if [ "$ETH_ENDPOINT" = "" ] || [ "$ETH_ACCOUNT" = "" ]; then
   echo Set ETH_ENDPOINT and ETH_ACCOUNT to use this script
   exit
fi

SECRET_PARAM=""
if [ "$ETH_SECRET" != "" ]; then
	SECRET_PARAM="--user :$ETH_SECRET"
fi

NONCE_HEX=`curl \
	-s \
	-X POST \
	-H "Content-Type: application/json" \
	$SECRET_PARAM \
	--data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["'$ETH_ACCOUNT'","latest"],"id":1}' \
	$ETH_ENDPOINT | jq -r .result`

echo $(($NONCE_HEX))
