#!/bin/sh

if [ "$ETH_ENDPOINT" = "" ]; then
   echo Set ETH_ENDPOINT to use this script
   exit
fi

SECRET_PARAM=""
if [ "$ETH_SECRET" != "" ]; then
	SECRET_PARAM="--user :$ETH_SECRET"
fi

GAS_IN_HEX=`curl \
	-s \
	-X POST \
	-H "Content-Type: application/json" \
	$SECRET_PARAM \
	--data '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":1}' \
	$ETH_ENDPOINT | jq -r .result`

GAS_IN_WEI=$(($GAS_IN_HEX))
GAS_IN_GWEI=`echo "scale=9; $GAS_IN_WEI / 1000000000" | bc`
GAS_IN_ETH=`echo "scale=9; $GAS_IN_GWEI / 1000000000" | bc`

echo "WEI:  $GAS_IN_WEI"
echo "GWEI: $GAS_IN_GWEI"
echo "ETH:  $GAS_IN_ETH"

